function main() {
    try {
        console.log('Hello World!')
    } catch (err) {
        console.error(err)
    }
}

main()
